#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'


# generated by racc

require 'strscan'
require "#{File.dirname(__FILE__)}/SecLangCore"

class SecLang < Racc::Parser

module_eval(<<'...end SecLang.y/module_eval...', 'SecLang.y', 316)
  attr_accessor :script

  def initialize
    @syntax_check = false
    @s = SecLangCore.new(self)
    @state = :MAIN
    @last_state = []
    @last_state.push @state
    @nested_stack = Array.new
    @depth = 0
  end

  def clear_tokens
    @tokens = []
  end

  def check_syntax( str )
    @syntax_check = true
    res = parse(str)
    @syntax_check = false
    @tokens = []
    return res
  end

  def parse(str)
    @script = str
    @tokens = [] if not @tokens
    scanner = StringScanner.new(str)
    
    until scanner.eos?
      case
        when @state == :MAIN
          case
            when m = scanner.scan(/puts/)
              @tokens.push [:PUTSTOK, m]
            when m = scanner.scan(/print/)
              @tokens.push [:PRINTTOK, m]
            when m = scanner.scan(/type/)
              @tokens.push [:TYPETOK, m]
            when m = scanner.scan(/mode/)
              @tokens.push [:GETMODETOK, m]
            when m = scanner.scan(/set_mode/)
              @tokens.push [:SETMODETOK, m]
            when m = scanner.scan(/\.\./)
              @tokens.push [:RANGETOK, m]
            when m = scanner.scan(/if/)
              @tokens.push [:IFTOK, m]
            when m = scanner.scan(/else/)
              @tokens.push [:ELSETOK, m]
            when m = scanner.scan(/while/)
              @tokens.push [:WHILETOK, m]
            when m = scanner.scan(/{/)
              @tokens.push [:OBRACE, m]
              @last_state.push @state
              @state = :CODE_BLOCK
              @code_blocks = Array.new
              @code_segment = String.new
              @depth = 1
            when m = scanner.scan(/\(/)
              @tokens.push [:LPAREN, m]
            when m = scanner.scan(/\)/)
              @tokens.push [:RPAREN, m]
            when m = scanner.scan(/\"/)
              @tokens.push [:QUOTE, m]
              @last_state.push @state
              @state = :QUOTED 
            when m = scanner.scan(/\'/)
              @tokens.push [:SINGLE_QUOTE, m]
              @last_state.push @state
              @state = :SINGLE_QUOTED
            when m = scanner.scan(/\/\*/)
              @last_state.push @state
              @state = :BLOCK_COMMENT
            when m = scanner.scan(/\[/)
              @tokens.push [:LBRACKET, m]
            when m = scanner.scan(/\]/)
              @tokens.push [:RBRACKET, m]
            when m = scanner.scan(/,/)
              @tokens.push [:COMMA, m]
            when m = scanner.scan(/=~/)
              @tokens.push [:MATCHTOK, m]
            when m = scanner.scan(/==/)
              @tokens.push [:EQ, m]
            when m = scanner.scan(/>=/)
              @tokens.push [:GE, m]
            when m = scanner.scan(/<=/)
              @tokens.push [:LE, m]
            when m = scanner.scan(/</)
              @tokens.push [:LT, m]
            when m = scanner.scan(/>/)
              @tokens.push [:GT, m]
            when m = scanner.scan(/!=/)
              @tokens.push [:NE, m]
            when m = scanner.scan(/\|\|/)
              @tokens.push [:ORTOK, m]
            when m = scanner.scan(/&&/)
              @tokens.push [:ANDTOK, m]
            when m = scanner.scan(/=/)
              @tokens.push [:EQUAL, m]
            when m = scanner.scan(/(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)/)
              @tokens.push [:IPV4ADDR, m]
            when m = scanner.scan(/\-{0,1}[0-9]+\.[0-9]+/)
              @tokens.push [:FLOAT, m]
            when m = scanner.scan(/0x[0-9a-fA-F]+/)
              @tokens.push [:HEXVALUE, m]
            when m = scanner.scan(/\+=/)
              @tokens.push [:VARINCAMT, m]
            when m = scanner.scan(/-=/)
              @tokens.push [:VARDECAMT, m]
            when m = scanner.scan(/def [a-zA-Z_][a-zA-Z0-9_]*\(/)
              @tokens.push [:DEFTOK, m]
              @last_state.push @state
              @state = :FUNC_DEFINE
            when m = scanner.scan(/[a-zA-Z_][a-zA-Z0-9_]*\(/)
              @tokens.push [:FUNCTOK, m]
            when m = scanner.scan(/:[a-zA-Z][a-zA-Z0-9_-]*/)
              @tokens.push [:SYMBOL, m]
            when m = scanner.scan(/[a-zA-Z][a-zA-Z0-9_]*\-\-/)
              @tokens.push [:VARDECTOK, m ]
            when m = scanner.scan(/[a-zA-Z][a-zA-Z0-9_]*\+\+/)
              @tokens.push [:VARINCTOK, m ]
            when m = scanner.scan(/[a-zA-Z][a-zA-Z0-9_]*/)
              @tokens.push [:VAR, m]
            when m = scanner.scan(/\-{0,1}[0-9]+/)
              @tokens.push [:DIGITS, m]
            when m = scanner.scan(/\+/)
              @tokens.push [:ADD, m]
            when m = scanner.scan(/\-/)
              @tokens.push [:SUB, m]
            when m = scanner.scan(/\*/)
              @tokens.push [:MULT, m]
            when m = scanner.scan(/\\/)
              @tokens.push [:DIV, m]
            when m = scanner.scan(/\`/)
              @tokens.push [:BACKTICK, m]
              @last_state.push @state
              @state = :BACKTICKS
            when m = scanner.scan(/;/)
              @tokens.push [:SEMICOLON, m]
            when scanner.scan(/[ \t\r\n]/)
              # ignore whtiespace
            else
              puts "Syntax error around #{scanner.pos} #{scanner.rest}"
              clear_tokens
              return nil
          end
       when @state == :BLOCK_COMMENT
         case
           when m = scanner.skip_until(/\*\//)
             @state = @last_state.pop
           when m = scanner.scan(/./)
           when m = scanner.scan(/[\r\n]/)
             # ignore
         end
       when @state == :FUNC_DEFINE
         case
           when m = scanner.scan(/\)/)
             @tokens.push [:RPAREN, m]
             @state = @last_state.pop
           when m = scanner.scan(/[^\)]+/)
             @tokens.push [:ARGS_DEF, m]
           when m = scanner.scan(/[ \t\r\n]/)
             # ignore whitespace
         end
       when @state == :BACKTICKS
         case
           when m = scanner.scan(/\`/)
             @tokens.push [:BACKTICK, m]
             @state = @last_state.pop
           when m = scanner.scan(/[^`]+/)
             @tokens.push [:DATA, m]
           when m = scanner.scan(/[ \t\r\n]/)
             # ignore whitespace
         end
       when @state == :CODE_BLOCK
         case
            when m = scanner.scan(/}/)
              @depth -= 1
              if @depth <= 0 then
                @state = @last_state.pop
                @code_blocks.push @code_segment
                @tokens.push [:BLOCK, @code_blocks]
                @tokens.push [:EBRACE, m]
                @depth = 0
              else
                @code_segment += m
              end
            when m = scanner.scan(/{/)
              @depth+= 1
              @code_segment += m
            when m = scanner.scan(/./)
              @code_segment += m
            when m = scanner.scan(/[\r\n]/)
              @code_segment += m
              @code_blocks.push @code_segment
              @code_segment = String.new
         end
       when @state == :QUOTED
         case
           when m = scanner.scan(/\"/)
             @tokens.push [:QUOTE, m]
             @state = @last_state.pop
           when m = scanner.scan(/[^"]+/)
             @tokens.push [:DATA, m]
           when m = scanner.scan(/[ \t\r\n]/)
             # ignore whitespace
         end
       when @state == :SINGLE_QUOTED
         case
           when m = scanner.scan(/\'/)
             @tokens.push [:SINGLE_QUOTE, m]
             @state = @last_state.pop
           when m = scanner.scan(/[^']+/)
             @tokens.push [:DATA, m]
           when m = scanner.scan(/[ \t\r\n]/)
             # ignore whitespace
         end

       end
    end
    #@tokens.push [false, false]

    if @last_state.size > 1 and not 
       (@state == :BLOCK_COMMENT or @state == :CODE_BLOCK) then
      puts "Unclosed brackets (#{@last_state.pop.to_s})"
      return -1
    end

    # Only parse @tokens when back at MAIN
    truth = nil
    if @last_state.size == 1 then
      @tokens.push [false, false]
      truth = yyparse(@tokens, :each)
      @tokens = []
    end
    return truth
  end

  def on_error(error_token_id, error_value, value_stack)
    msg = "parse error "
    msg << "after #{value_stack.last} " if value_stack.length > 1
    msg << "on #{token_to_str(error_token_id)} #{error_value}"
    msg << "\n#{@tokens.inspect}"
    clear_tokens
    raise ParseError, msg
  end

  def loop
    @tokens = @nested_stack.pop
    yyparse(@tokens, :each) if @tokens.size > 0
  end

...end SecLang.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     2,    61,   123,    62,    97,    98,    60,   111,   112,   113,
   114,   115,   116,    77,    76,   101,   102,     7,     8,     9,
    61,    75,    62,    63,    10,    14,    15,    16,    17,    18,
    19,   103,    20,    29,     2,    30,   104,    31,   105,    32,
    33,    60,    34,    35,   106,    36,   107,   108,    37,    38,
   109,     7,     8,     9,   110,    61,    74,    62,    10,    14,
    15,    16,    17,    18,    19,   117,    20,    29,     2,    30,
   118,    31,   119,    32,    33,    73,    34,    35,   121,    36,
   122,    78,    37,    38,   124,     7,     8,     9,    72,    71,
    69,    59,    10,    14,    15,    16,    17,    18,    19,    58,
    20,    29,     2,    30,    39,    31,   131,    32,    33,   132,
    34,    35,   133,    36,   134,   135,    37,    38,   136,     7,
     8,     9,   137,   138,   139,   140,    10,    14,    15,    16,
    17,    18,    19,   141,    20,    29,     2,    30,   142,    31,
   143,    32,    33,   144,    34,    35,   nil,    36,   nil,   nil,
    37,    38,   nil,     7,     8,     9,   nil,   nil,   nil,   nil,
    10,    14,    15,    16,    17,    18,    19,   nil,    20,    29,
     2,    30,   nil,    31,   nil,    32,    33,   nil,    34,    35,
   nil,    36,   nil,   nil,    37,    38,   nil,     7,     8,     9,
   nil,   nil,   nil,   nil,    10,    14,    15,    16,    17,    18,
    19,   nil,    20,    29,     2,    30,   nil,    31,   nil,    32,
    33,   nil,    34,    35,   nil,    36,   nil,   nil,    37,    38,
   nil,     7,     8,     9,   nil,   nil,   nil,   nil,    10,    14,
    15,    16,    17,    18,    19,   nil,    20,    29,     2,    30,
   nil,    31,   nil,    32,    33,   nil,    34,    35,   nil,    36,
   nil,   nil,    37,    38,   nil,     7,     8,     9,   nil,   nil,
   nil,   nil,    10,    14,    15,    16,    17,    18,    19,   nil,
    20,    29,     2,    30,   nil,    31,   nil,    32,    33,   nil,
    34,    35,   nil,    36,   nil,   nil,    37,    38,   nil,     7,
     8,     9,   nil,   nil,   nil,   nil,    10,    14,    15,    16,
    17,    18,    19,   nil,    20,    29,     2,    30,   nil,    31,
   nil,    32,    33,   nil,    34,    35,   nil,    36,   nil,   nil,
    37,    38,   nil,     7,     8,     9,   nil,   nil,   nil,   nil,
    10,    14,    15,    16,    17,    18,    19,   nil,    20,    29,
     2,    30,   nil,    31,   nil,    32,    33,   nil,    34,    35,
   nil,    36,   nil,   nil,    37,    38,   nil,     7,     8,     9,
   nil,   nil,   nil,   nil,    10,    14,    15,    16,    17,    18,
    19,   nil,    20,    29,     2,    30,   nil,    31,   nil,    32,
    33,   nil,    34,    35,   nil,    36,   nil,   nil,    37,    38,
   nil,     7,     8,     9,   nil,   nil,   nil,   nil,    10,    14,
    15,    16,    17,    18,    19,   nil,    20,    29,     2,    30,
   nil,    31,   nil,    32,    33,   nil,    34,    35,   nil,    36,
   nil,   nil,    37,    38,   nil,     7,     8,     9,   nil,   nil,
   nil,   nil,    10,    14,    15,    16,    17,    18,    19,   nil,
    20,    29,     2,    30,   nil,    31,   nil,    32,    33,   nil,
    34,    35,   nil,    36,   nil,   nil,    37,    38,   nil,     7,
     8,     9,   nil,   nil,   nil,   nil,    10,    14,    15,    16,
    17,    18,    19,   nil,    20,    29,     2,    30,   nil,    31,
   nil,    32,    33,   nil,    34,    35,   nil,    36,   nil,   nil,
    37,    38,   nil,     7,     8,     9,   nil,   nil,   nil,   nil,
    10,    14,    15,    16,    17,    18,    19,   nil,    20,    29,
     2,    30,   nil,    31,   nil,    32,    33,   nil,    34,    35,
   nil,    36,   nil,   nil,    37,    38,   nil,     7,     8,     9,
   nil,   nil,   nil,   nil,    10,    14,    15,    16,    17,    18,
    19,   nil,    20,    29,     2,    30,   nil,    31,   nil,    32,
    33,   nil,    34,    35,   nil,    36,   nil,   nil,    37,    38,
   nil,     7,     8,     9,   nil,   nil,   nil,   nil,    10,    14,
    15,    16,    17,    18,    19,   nil,    20,    29,     2,    30,
   nil,    31,   nil,    32,    33,   nil,    34,    35,   nil,    36,
   nil,   nil,    37,    38,   nil,     7,     8,     9,   nil,   nil,
   nil,   nil,    10,    14,    15,    16,    17,    18,    19,   nil,
    20,    29,     2,    30,   nil,    31,   nil,    32,    33,   nil,
    34,    35,   nil,    36,   nil,   nil,    37,    38,   nil,     7,
     8,     9,   nil,   nil,   nil,   nil,    10,    14,    15,    16,
    17,    18,    19,   nil,    20,    29,     2,    30,   nil,    31,
   nil,    32,    33,   nil,    34,    35,   nil,    36,   nil,   nil,
    37,    38,   nil,     7,     8,     9,   nil,   nil,   nil,   nil,
    10,    14,    15,    16,    17,    18,    19,   nil,    20,    29,
     2,    30,   nil,    31,   nil,    32,    33,   nil,    34,    35,
   nil,    36,   nil,   nil,    37,    38,   nil,     7,     8,     9,
   nil,   nil,   nil,   nil,    10,    14,    15,    16,    17,    18,
    19,   nil,    20,    29,     2,    30,   nil,    31,   nil,    32,
    33,   nil,    34,    35,   nil,    36,   nil,   nil,    37,    38,
   nil,     7,     8,     9,   nil,   nil,   nil,   nil,    10,    14,
    15,    16,    17,    18,    19,   nil,    20,    29,     2,    30,
   nil,    31,   nil,    32,    33,   nil,    34,    35,   nil,    36,
   nil,   nil,    37,    38,   nil,     7,     8,     9,   nil,   nil,
   nil,   nil,    10,    14,    15,    16,    17,    18,    19,   nil,
    20,    29,     2,    30,   nil,    31,   nil,    32,    33,   nil,
    34,    35,   nil,    36,   nil,   nil,    37,    38,   nil,     7,
     8,     9,   nil,   nil,   nil,   nil,    10,    14,    15,    16,
    17,    18,    19,   nil,    20,    29,     2,    30,   nil,    31,
   nil,    32,    33,   nil,    34,    35,   nil,    36,   nil,   nil,
    37,    38,   nil,     7,     8,     9,   nil,   nil,   nil,   nil,
    10,    14,    15,    16,    17,    18,    19,   nil,    20,    29,
     2,    30,   nil,    31,   nil,    32,    33,   nil,    34,    35,
   nil,    36,   nil,   nil,    37,    38,   nil,     7,     8,     9,
   nil,   nil,   nil,   nil,    10,    14,    15,    16,    17,    18,
    19,   nil,    20,    29,     2,    30,   nil,    31,   nil,    32,
    33,   nil,    34,    35,   nil,    36,   nil,   nil,    37,    38,
   nil,     7,     8,     9,   nil,   nil,   nil,   nil,    10,    14,
    15,    16,    17,    18,    19,   nil,    20,    29,   nil,    30,
   nil,    31,   nil,    32,    33,   nil,    34,    35,   nil,    36,
   nil,   nil,    37,    38,    14,    15,    64,    17,    18,    19,
   nil,    20,    29,   nil,    30,   nil,    31,   nil,    32,    33,
   nil,    34,    35,   nil,    36,   nil,   nil,    37,    38,    14,
    15,    64,    17,    18,    19,   nil,    20,    29,   nil,    30,
   nil,    31,   nil,    32,    33,   nil,    34,    35,   nil,    36,
   nil,   nil,    37,    38,    14,    15,    64,    17,    18,    19,
   nil,    20,    29,   nil,    30,   nil,    31,   nil,    32,    33,
   nil,    34,    35,   nil,    36,   nil,   nil,    37,    38,    14,
    15,    64,    17,    18,    19,   nil,    20,    29,   nil,    30,
   nil,    31,   nil,    32,    33,   nil,    34,    35,   nil,    36,
   nil,   nil,    37,    38,    14,    15,    64,    17,    18,    19,
   nil,    20,    29,   nil,    30,   nil,    31,   nil,    32,    33,
   nil,    34,    35,   nil,    36,   nil,   nil,    37,    38,    14,
    15,    64,    17,    18,    19,   nil,    20,    29,   nil,    30,
   nil,    31,   nil,    32,    33,   nil,    34,    35,    68,    36,
   nil,   nil,    37,    38,    29,   nil,    30,   nil,    31,   nil,
    32,    33,   nil,    34,    35,   nil,    36,    42,    43,    51,
    52,    53,    54,    41,    44,    45,    46,    47,    48,    49,
    50,    55 ]

racc_action_check = [
     0,    68,   107,    68,    61,    61,    16,    78,    78,    78,
    78,    78,    78,    39,    38,    65,    66,     0,     0,     0,
    16,    37,    16,    16,     0,     0,     0,     0,     0,     0,
     0,    69,     0,     0,   116,     0,    70,     0,    71,     0,
     0,    64,     0,     0,    72,     0,    73,    74,     0,     0,
    75,   116,   116,   116,    76,    64,    34,    64,   116,   116,
   116,   116,   116,   116,   116,    94,   116,   116,     2,   116,
    95,   116,    96,   116,   116,    33,   116,   116,   103,   116,
   106,    40,   116,   116,   108,     2,     2,     2,    32,    31,
    29,    10,     2,     2,     2,     2,     2,     2,     2,     9,
     2,     2,    50,     2,     1,     2,   117,     2,     2,   118,
     2,     2,   121,     2,   123,   131,     2,     2,   132,    50,
    50,    50,   133,   134,   135,   136,    50,    50,    50,    50,
    50,    50,    50,   139,    50,    50,     7,    50,   141,    50,
   142,    50,    50,   143,    50,    50,   nil,    50,   nil,   nil,
    50,    50,   nil,     7,     7,     7,   nil,   nil,   nil,   nil,
     7,     7,     7,     7,     7,     7,     7,   nil,     7,     7,
     8,     7,   nil,     7,   nil,     7,     7,   nil,     7,     7,
   nil,     7,   nil,   nil,     7,     7,   nil,     8,     8,     8,
   nil,   nil,   nil,   nil,     8,     8,     8,     8,     8,     8,
     8,   nil,     8,     8,   115,     8,   nil,     8,   nil,     8,
     8,   nil,     8,     8,   nil,     8,   nil,   nil,     8,     8,
   nil,   115,   115,   115,   nil,   nil,   nil,   nil,   115,   115,
   115,   115,   115,   115,   115,   nil,   115,   115,   114,   115,
   nil,   115,   nil,   115,   115,   nil,   115,   115,   nil,   115,
   nil,   nil,   115,   115,   nil,   114,   114,   114,   nil,   nil,
   nil,   nil,   114,   114,   114,   114,   114,   114,   114,   nil,
   114,   114,    59,   114,   nil,   114,   nil,   114,   114,   nil,
   114,   114,   nil,   114,   nil,   nil,   114,   114,   nil,    59,
    59,    59,   nil,   nil,   nil,   nil,    59,    59,    59,    59,
    59,    59,    59,   nil,    59,    59,    49,    59,   nil,    59,
   nil,    59,    59,   nil,    59,    59,   nil,    59,   nil,   nil,
    59,    59,   nil,    49,    49,    49,   nil,   nil,   nil,   nil,
    49,    49,    49,    49,    49,    49,    49,   nil,    49,    49,
    58,    49,   nil,    49,   nil,    49,    49,   nil,    49,    49,
   nil,    49,   nil,   nil,    49,    49,   nil,    58,    58,    58,
   nil,   nil,   nil,   nil,    58,    58,    58,    58,    58,    58,
    58,   nil,    58,    58,   113,    58,   nil,    58,   nil,    58,
    58,   nil,    58,    58,   nil,    58,   nil,   nil,    58,    58,
   nil,   113,   113,   113,   nil,   nil,   nil,   nil,   113,   113,
   113,   113,   113,   113,   113,   nil,   113,   113,    48,   113,
   nil,   113,   nil,   113,   113,   nil,   113,   113,   nil,   113,
   nil,   nil,   113,   113,   nil,    48,    48,    48,   nil,   nil,
   nil,   nil,    48,    48,    48,    48,    48,    48,    48,   nil,
    48,    48,   112,    48,   nil,    48,   nil,    48,    48,   nil,
    48,    48,   nil,    48,   nil,   nil,    48,    48,   nil,   112,
   112,   112,   nil,   nil,   nil,   nil,   112,   112,   112,   112,
   112,   112,   112,   nil,   112,   112,   111,   112,   nil,   112,
   nil,   112,   112,   nil,   112,   112,   nil,   112,   nil,   nil,
   112,   112,   nil,   111,   111,   111,   nil,   nil,   nil,   nil,
   111,   111,   111,   111,   111,   111,   111,   nil,   111,   111,
    47,   111,   nil,   111,   nil,   111,   111,   nil,   111,   111,
   nil,   111,   nil,   nil,   111,   111,   nil,    47,    47,    47,
   nil,   nil,   nil,   nil,    47,    47,    47,    47,    47,    47,
    47,   nil,    47,    47,    46,    47,   nil,    47,   nil,    47,
    47,   nil,    47,    47,   nil,    47,   nil,   nil,    47,    47,
   nil,    46,    46,    46,   nil,   nil,   nil,   nil,    46,    46,
    46,    46,    46,    46,    46,   nil,    46,    46,    54,    46,
   nil,    46,   nil,    46,    46,   nil,    46,    46,   nil,    46,
   nil,   nil,    46,    46,   nil,    54,    54,    54,   nil,   nil,
   nil,   nil,    54,    54,    54,    54,    54,    54,    54,   nil,
    54,    54,    53,    54,   nil,    54,   nil,    54,    54,   nil,
    54,    54,   nil,    54,   nil,   nil,    54,    54,   nil,    53,
    53,    53,   nil,   nil,   nil,   nil,    53,    53,    53,    53,
    53,    53,    53,   nil,    53,    53,    63,    53,   nil,    53,
   nil,    53,    53,   nil,    53,    53,   nil,    53,   nil,   nil,
    53,    53,   nil,    63,    63,    63,   nil,   nil,   nil,   nil,
    63,    63,    63,    63,    63,    63,    63,   nil,    63,    63,
    52,    63,   nil,    63,   nil,    63,    63,   nil,    63,    63,
   nil,    63,   nil,   nil,    63,    63,   nil,    52,    52,    52,
   nil,   nil,   nil,   nil,    52,    52,    52,    52,    52,    52,
    52,   nil,    52,    52,    41,    52,   nil,    52,   nil,    52,
    52,   nil,    52,    52,   nil,    52,   nil,   nil,    52,    52,
   nil,    41,    41,    41,   nil,   nil,   nil,   nil,    41,    41,
    41,    41,    41,    41,    41,   nil,    41,    41,    42,    41,
   nil,    41,   nil,    41,    41,   nil,    41,    41,   nil,    41,
   nil,   nil,    41,    41,   nil,    42,    42,    42,   nil,   nil,
   nil,   nil,    42,    42,    42,    42,    42,    42,    42,   nil,
    42,    42,    43,    42,   nil,    42,   nil,    42,    42,   nil,
    42,    42,   nil,    42,   nil,   nil,    42,    42,   nil,    43,
    43,    43,   nil,   nil,   nil,   nil,    43,    43,    43,    43,
    43,    43,    43,   nil,    43,    43,    44,    43,   nil,    43,
   nil,    43,    43,   nil,    43,    43,   nil,    43,   nil,   nil,
    43,    43,   nil,    44,    44,    44,   nil,   nil,   nil,   nil,
    44,    44,    44,    44,    44,    44,    44,   nil,    44,    44,
    45,    44,   nil,    44,   nil,    44,    44,   nil,    44,    44,
   nil,    44,   nil,   nil,    44,    44,   nil,    45,    45,    45,
   nil,   nil,   nil,   nil,    45,    45,    45,    45,    45,    45,
    45,   nil,    45,    45,    51,    45,   nil,    45,   nil,    45,
    45,   nil,    45,    45,   nil,    45,   nil,   nil,    45,    45,
   nil,    51,    51,    51,   nil,   nil,   nil,   nil,    51,    51,
    51,    51,    51,    51,    51,   nil,    51,    51,   nil,    51,
   nil,    51,   nil,    51,    51,   nil,    51,    51,   nil,    51,
   nil,   nil,    51,    51,   102,   102,   102,   102,   102,   102,
   nil,   102,   102,   nil,   102,   nil,   102,   nil,   102,   102,
   nil,   102,   102,   nil,   102,   nil,   nil,   102,   102,    30,
    30,    30,    30,    30,    30,   nil,    30,    30,   nil,    30,
   nil,    30,   nil,    30,    30,   nil,    30,    30,   nil,    30,
   nil,   nil,    30,    30,    19,    19,    19,    19,    19,    19,
   nil,    19,    19,   nil,    19,   nil,    19,   nil,    19,    19,
   nil,    19,    19,   nil,    19,   nil,   nil,    19,    19,    60,
    60,    60,    60,    60,    60,   nil,    60,    60,   nil,    60,
   nil,    60,   nil,    60,    60,   nil,    60,    60,   nil,    60,
   nil,   nil,    60,    60,    55,    55,    55,    55,    55,    55,
   nil,    55,    55,   nil,    55,   nil,    55,   nil,    55,    55,
   nil,    55,    55,   nil,    55,   nil,   nil,    55,    55,    62,
    62,    62,    62,    62,    62,   nil,    62,    62,   nil,    62,
   nil,    62,   nil,    62,    62,   nil,    62,    62,    20,    62,
   nil,   nil,    62,    62,    20,   nil,    20,   nil,    20,   nil,
    20,    20,   nil,    20,    20,   nil,    20,     4,     4,     4,
     4,     4,     4,     4,     4,     4,     4,     4,     4,     4,
     4,     4 ]

racc_action_pointer = [
    -2,   104,    66,   nil,  1093,   nil,   nil,   134,   168,    97,
    89,   nil,   nil,   nil,   nil,   nil,   -26,   nil,   nil,   957,
  1049,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    54,
   932,    49,    86,    73,    54,   nil,   nil,   -19,   -26,    13,
    78,   712,   746,   780,   814,   848,   542,   508,   406,   304,
   100,   882,   678,   610,   576,  1007,   nil,   nil,   338,   270,
   982,   -24,  1032,   644,     9,   -18,   -22,   nil,   -45,    28,
    33,    -1,    15,    17,    18,     0,     3,   nil,     3,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    62,    67,    39,   nil,   nil,   nil,
   nil,   nil,   907,    56,   nil,   nil,    77,   -36,    81,   nil,
   nil,   474,   440,   372,   236,   202,    32,    84,    87,   nil,
   nil,    89,   nil,    71,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    92,    95,    98,   120,   100,   101,   nil,   nil,   108,
   nil,   116,   117,   119,   nil ]

racc_action_default = [
    -1,   -68,    -1,    -8,   -28,   -10,   -11,    -1,    -1,   -68,
   -68,   -32,   -33,   -34,   -35,   -36,   -37,   -38,   -39,   -53,
   -68,   -43,   -44,   -45,   -46,   -47,   -48,   -49,   -50,   -68,
   -53,   -68,   -68,   -68,   -68,   -60,   -63,   -68,   -68,   -68,
   -68,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,   -68,   -26,   -27,    -1,    -1,
   -68,   -68,   -68,    -1,   -37,   -68,   -54,   -42,   -68,   -68,
   -68,   -68,   -68,   -68,   -68,   -68,   -68,   145,   -68,    -9,
   -12,   -13,   -14,   -15,   -16,   -17,   -18,   -19,   -20,   -21,
   -22,   -23,   -24,   -25,   -68,   -68,   -68,   -61,   -62,   -64,
   -65,   -41,   -53,   -68,   -52,   -56,   -68,   -68,   -68,   -66,
   -67,    -1,    -1,    -1,    -1,    -1,    -1,   -68,   -68,   -40,
   -55,   -68,   -57,   -68,   -59,    -2,    -3,    -4,    -5,    -6,
    -7,   -68,   -68,   -68,   -68,   -68,   -68,   -51,   -58,   -30,
   -31,   -68,   -68,   -68,   -29 ]

racc_goto_table = [
     1,    65,    40,    67,   nil,   nil,   nil,    56,    57,   nil,
   nil,   nil,    70,   nil,   nil,   nil,   nil,   nil,   nil,    66,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    66,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    79,    80,    81,    82,    83,    84,    85,    86,    87,
    88,    89,    90,    91,    92,    93,   nil,   nil,    94,    95,
    96,   nil,    99,   100,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   120,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    66,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   125,   126,   127,   128,   129,   130 ]

racc_goto_check = [
     1,     9,     1,     6,   nil,   nil,   nil,     1,     1,   nil,
   nil,   nil,     9,   nil,   nil,   nil,   nil,   nil,   nil,     3,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     3,   nil,   nil,     1,     1,
     3,   nil,     3,     1,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     9,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     1,     1,     1,     1,     1,     1 ]

racc_goto_pointer = [
   nil,     0,   nil,     0,   nil,   nil,   -17,   nil,   nil,   -18,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,     3,     4,     5,     6,    11,    12,    13,   nil,
    21,    22,    23,    24,    25,    26,    27,    28 ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 53, :_reduce_1,
  5, 53, :_reduce_2,
  5, 53, :_reduce_3,
  5, 53, :_reduce_4,
  5, 53, :_reduce_5,
  5, 53, :_reduce_6,
  5, 53, :_reduce_7,
  1, 53, :_reduce_none,
  3, 53, :_reduce_none,
  1, 53, :_reduce_none,
  1, 53, :_reduce_none,
  3, 53, :_reduce_12,
  3, 53, :_reduce_13,
  3, 53, :_reduce_14,
  3, 53, :_reduce_15,
  3, 53, :_reduce_16,
  3, 53, :_reduce_17,
  3, 53, :_reduce_18,
  3, 53, :_reduce_19,
  3, 53, :_reduce_20,
  3, 53, :_reduce_21,
  3, 53, :_reduce_22,
  3, 53, :_reduce_23,
  3, 53, :_reduce_24,
  3, 53, :_reduce_25,
  2, 53, :_reduce_26,
  2, 53, :_reduce_27,
  1, 53, :_reduce_none,
  11, 56, :_reduce_29,
  7, 56, :_reduce_30,
  7, 57, :_reduce_31,
  1, 55, :_reduce_none,
  1, 55, :_reduce_none,
  1, 55, :_reduce_34,
  1, 55, :_reduce_35,
  1, 55, :_reduce_36,
  1, 55, :_reduce_37,
  1, 55, :_reduce_38,
  1, 55, :_reduce_39,
  4, 55, :_reduce_40,
  3, 55, :_reduce_41,
  2, 59, :_reduce_42,
  1, 58, :_reduce_none,
  1, 58, :_reduce_none,
  1, 58, :_reduce_none,
  1, 58, :_reduce_none,
  1, 58, :_reduce_none,
  1, 58, :_reduce_none,
  1, 58, :_reduce_none,
  1, 58, :_reduce_none,
  6, 69, :_reduce_51,
  3, 68, :_reduce_52,
  0, 61, :_reduce_53,
  1, 61, :_reduce_54,
  3, 61, :_reduce_55,
  3, 67, :_reduce_56,
  4, 62, :_reduce_57,
  6, 65, :_reduce_58,
  4, 63, :_reduce_59,
  1, 64, :_reduce_60,
  3, 64, :_reduce_61,
  3, 64, :_reduce_62,
  1, 66, :_reduce_63,
  3, 66, :_reduce_64,
  3, 54, :_reduce_65,
  3, 60, :_reduce_66,
  3, 60, :_reduce_67 ]

racc_reduce_n = 68

racc_shift_n = 145

racc_token_table = {
  false => 0,
  :error => 1,
  :LPAREN => 2,
  :RPAREN => 3,
  :ANDTOK => 4,
  :ORTOK => 5,
  :ADD => 6,
  :SUB => 7,
  :MULT => 8,
  :DIV => 9,
  :SEMICOLON => 10,
  :MATCHTOK => 11,
  :EQ => 12,
  :GT => 13,
  :LT => 14,
  :LE => 15,
  :GE => 16,
  :NE => 17,
  :RANGETOK => 18,
  :PUTSTOK => 19,
  :PRINTTOK => 20,
  :IFTOK => 21,
  :OBRACE => 22,
  :BLOCK => 23,
  :EBRACE => 24,
  :ELSETOK => 25,
  :WHILETOK => 26,
  :FLOAT => 27,
  :DIGITS => 28,
  :VAR => 29,
  :HEXVALUE => 30,
  :IPV4ADDR => 31,
  :LBRACKET => 32,
  :RBRACKET => 33,
  :NOTTOK => 34,
  :DEFTOK => 35,
  :ARGS_DEF => 36,
  :FUNCTOK => 37,
  :COMMA => 38,
  :BACKTICK => 39,
  :DATA => 40,
  :TYPETOK => 41,
  :SETMODETOK => 42,
  :SYMBOL => 43,
  :GETMODETOK => 44,
  :VARDECTOK => 45,
  :VARDECAMT => 46,
  :VARINCTOK => 47,
  :VARINCAMT => 48,
  :EQUAL => 49,
  :QUOTE => 50,
  :SINGLE_QUOTE => 51 }

racc_nt_base = 52

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "LPAREN",
  "RPAREN",
  "ANDTOK",
  "ORTOK",
  "ADD",
  "SUB",
  "MULT",
  "DIV",
  "SEMICOLON",
  "MATCHTOK",
  "EQ",
  "GT",
  "LT",
  "LE",
  "GE",
  "NE",
  "RANGETOK",
  "PUTSTOK",
  "PRINTTOK",
  "IFTOK",
  "OBRACE",
  "BLOCK",
  "EBRACE",
  "ELSETOK",
  "WHILETOK",
  "FLOAT",
  "DIGITS",
  "VAR",
  "HEXVALUE",
  "IPV4ADDR",
  "LBRACKET",
  "RBRACKET",
  "NOTTOK",
  "DEFTOK",
  "ARGS_DEF",
  "FUNCTOK",
  "COMMA",
  "BACKTICK",
  "DATA",
  "TYPETOK",
  "SETMODETOK",
  "SYMBOL",
  "GETMODETOK",
  "VARDECTOK",
  "VARDECAMT",
  "VARINCTOK",
  "VARINCAMT",
  "EQUAL",
  "QUOTE",
  "SINGLE_QUOTE",
  "$start",
  "commands",
  "variable_assignment",
  "truth_stmt",
  "if_stmt",
  "while_stmt",
  "command",
  "not_command",
  "quotedtext",
  "args",
  "type_cmd",
  "get_mode_cmd",
  "vardec_cmd",
  "set_mode_cmd",
  "varinc_cmd",
  "backtick_cmd",
  "call_func",
  "define_func" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'SecLang.y', 5)
  def _reduce_1(val, _values, result)
     result = false 
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 8)
  def _reduce_2(val, _values, result)
                 result = val[1] && val[4]
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 12)
  def _reduce_3(val, _values, result)
                 result = val[1] || val[4]
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 16)
  def _reduce_4(val, _values, result)
                 result = @s.var_add_var(val[1], val[4])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 20)
  def _reduce_5(val, _values, result)
                 result = @s.var_sub_var(val[1], val[4])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 24)
  def _reduce_6(val, _values, result)
                 result = @s.var_mult_var(val[1], val[4])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 28)
  def _reduce_7(val, _values, result)
                 result = @s.var_div_var(val[1], val[4])
           
    result
  end
.,.,

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

module_eval(<<'.,.,', 'SecLang.y', 36)
  def _reduce_12(val, _values, result)
                 result = val[0] && val[2]
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 40)
  def _reduce_13(val, _values, result)
                 result = val[0] || val[2]
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 45)
  def _reduce_14(val, _values, result)
                 result = @s.is_match?(val[0], val[2])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 50)
  def _reduce_15(val, _values, result)
                 result = @s.is_eq?(val[0], val[2])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 55)
  def _reduce_16(val, _values, result)
                 result = @s.is_gt?(val[0],val[2])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 60)
  def _reduce_17(val, _values, result)
                 result = @s.is_lt?(val[0],val[2])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 65)
  def _reduce_18(val, _values, result)
                 result = @s.is_le?(val[0],val[2])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 70)
  def _reduce_19(val, _values, result)
                 result = @s.is_ge?(val[0],val[2])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 75)
  def _reduce_20(val, _values, result)
                 result = @s.is_ne?(val[0],val[2])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 80)
  def _reduce_21(val, _values, result)
                 result = @s.var_add_var(val[0], val[2])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 85)
  def _reduce_22(val, _values, result)
                 result = @s.var_sub_var(val[0], val[2])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 90)
  def _reduce_23(val, _values, result)
                 result = @s.var_mult_var(val[0], val[2])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 95)
  def _reduce_24(val, _values, result)
                 result = @s.var_div_var(val[0], val[2])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 100)
  def _reduce_25(val, _values, result)
    		result = @s.var_range(val[0], val[2])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 105)
  def _reduce_26(val, _values, result)
                 result = @s.sec_puts(val[1])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 110)
  def _reduce_27(val, _values, result)
                 result = @s.sec_print(val[1])
           
    result
  end
.,.,

# reduce 28 omitted

module_eval(<<'.,.,', 'SecLang.y', 118)
  def _reduce_29(val, _values, result)
    		result = @s.if_stmt(val[2], val[5], val[9])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 123)
  def _reduce_30(val, _values, result)
    		result = @s.if_stmt(val[2], val[5])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 130)
  def _reduce_31(val, _values, result)
                    @nested_stack.push @tokens
 		result = @s.while_stmt(val[2], val[5])
           
    result
  end
.,.,

# reduce 32 omitted

# reduce 33 omitted

module_eval(<<'.,.,', 'SecLang.y', 142)
  def _reduce_34(val, _values, result)
    		result = StringVar.new(val[0])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 147)
  def _reduce_35(val, _values, result)
    		result = FloatVar.new(val[0])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 152)
  def _reduce_36(val, _values, result)
    		result = IntVar.new(val[0])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 157)
  def _reduce_37(val, _values, result)
                    result = @s.get_var(val[0])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 162)
  def _reduce_38(val, _values, result)
    		result = HexVar.new(val[0])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 167)
  def _reduce_39(val, _values, result)
    		result = IPv4Var.new(val[0])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 172)
  def _reduce_40(val, _values, result)
    		result = @s.slice_var(val[0], val[2])
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 177)
  def _reduce_41(val, _values, result)
    		result = ArrayVar.new(val[1].flatten)
           
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 184)
  def _reduce_42(val, _values, result)
                      result = val[1] ? false : true
           
    result
  end
.,.,

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

module_eval(<<'.,.,', 'SecLang.y', 209)
  def _reduce_51(val, _values, result)
    		result = @s.add_func(val[0], val[1], val[4])
          
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 216)
  def _reduce_52(val, _values, result)
    		result = @s.call_func(val[0], val[1].flatten)
          
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 220)
  def _reduce_53(val, _values, result)
     result = nil 
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 221)
  def _reduce_54(val, _values, result)
     result = [val[0] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 222)
  def _reduce_55(val, _values, result)
     result = [val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 228)
  def _reduce_56(val, _values, result)
    		result = @s.shell(val[1])
          
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 235)
  def _reduce_57(val, _values, result)
    		result = @s.var_type(val[2])
          
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 242)
  def _reduce_58(val, _values, result)
    		result = @s.var_set_mode(val[2], val[4])
          
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 249)
  def _reduce_59(val, _values, result)
    		result = @s.var_get_mode(val[2])
          
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 256)
  def _reduce_60(val, _values, result)
    		result = @s.var_dec(val[0])
          
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 261)
  def _reduce_61(val, _values, result)
    		result = @s.var_dec(val[0], val[2])
          
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 266)
  def _reduce_62(val, _values, result)
                 	result = @s.var_dec_var(val[0], val[2])
          
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 273)
  def _reduce_63(val, _values, result)
    		result = @s.var_inc(val[0])
          
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 283)
  def _reduce_64(val, _values, result)
                 	result = @s.var_inc_var(val[0], val[2])
          
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 290)
  def _reduce_65(val, _values, result)
    		result = @s.add_var(val[0], val[2])
          
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 297)
  def _reduce_66(val, _values, result)
    		result = val[1]
         
    result
  end
.,.,

module_eval(<<'.,.,', 'SecLang.y', 301)
  def _reduce_67(val, _values, result)
    		result = val[1]
         
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class SecLang


